### ISSUE TITLE
App previously rejected by appstore

### ISSUE THREAD

**Issue by MikeysBoard** [turnkeymobileapps/help-center#33]
Time to renew subscription but wanted to know if it can be resubmitted if I do.

**Comment by vbresults** [comment]
This app was tentatively rejected by Apple due to their contest rules, which could have been remedied with some changes.  We attempted to make contact with you several times to resolve this.

If the app is now in compliance with Apple's contest rules and you request the iPhone app to be resubmitted, it can be done within a few days.

**Comment by MikeysBoard** [comment]
Please resubmit. Raffles are no longer on site

**Comment by vbresults** [comment]
Confirmed; it will be back up in a few days and a notification will be sent at that time.

**Comment by MikeysBoard** [comment]
Any update on the re-submission?

**Comment by vbresults** [comment]
Replying by email
